REM complete_ngrok_fix.bat
@echo off
color 0C
echo ========================================
echo 🚨 COMPLETE NGROK BROWSER WARNING FIX
echo ========================================

echo 🔍 Problem Analysis:
echo   ❌ Ngrok browser warning blocking API calls
echo   ❌ Frontend receiving HTML instead of JSON
echo   ❌ Vue components expecting Array but getting String
echo.

REM Stop current processes
echo 🛑 Stopping current processes...
taskkill /f /im node.exe 2>nul
timeout /t 3

REM Get backend URL
echo 📡 Backend Configuration:
echo.
echo Please enter your ngrok backend URL:
echo Example: https://da288609b4bb.ngrok-free.app
echo.
set /p BACKEND_URL="Backend URL: "

if "%BACKEND_URL%"=="" (
    echo ❌ No backend URL provided, using localhost
    set BACKEND_URL=http://localhost:8000
)

REM Clean URL (remove trailing slash)
if "%BACKEND_URL:~-1%"=="/" set BACKEND_URL=%BACKEND_URL:~0,-1%

echo ✅ Using backend: %BACKEND_URL%

REM Setup WebSocket URL
set WS_URL=%BACKEND_URL%
if "%BACKEND_URL:~0,8%"=="https://" (
    set WS_URL=%BACKEND_URL:https://=wss://%
) else (
    set WS_URL=%BACKEND_URL:http://=ws://%
)

echo.
echo 🔧 Applying comprehensive fixes...

cd /d %~dp0\frontend

REM 1. Create proper .env file
echo 📝 Creating environment configuration...
(
echo # Truck Management System - Ngrok Configuration
echo # Auto-generated by complete_ngrok_fix.bat
echo.
echo # Backend API URL
echo VITE_API_BASE_URL=%BACKEND_URL%
echo.
echo # WebSocket URL
echo VITE_WS_URL=%WS_URL%/ws
echo.
echo # Ngrok bypass settings
echo VITE_BYPASS_NGROK_WARNING=true
echo